services:
  postgres_db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: db_dev
      POSTGRES_USER: user_dev
      POSTGRES_PASSWORD: pass_dev
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'

  pgbouncer:
    image: edoburu/pgbouncer:latest
    restart: always
    environment:
      - 'DB_USER=user_dev'
      - 'DB_PASSWORD=pass_dev'
      - 'DB_HOST=postgres_db'
      - 'MAX_CLIENT_CONN=500'
      - 'DEFAULT_POOL_SIZE=50'
      - 'SERVER_IDLE_TIMEOUT=60'
      - 'DB_NAME=db_dev'
      - 'AUTH_TYPE=md5'
      - 'AUTH_FILE=/etc/pgbouncer/userlist.txt'
    volumes:
      - ./postgres/userlist.txt:/etc/pgbouncer/userlist.txt
    depends_on:
      - postgres_db

  backend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres_db
    ports:
      - 8000:8000
    volumes:
      - ./src:/app/src
      - ./src/migrations:/app/src/migrations
volumes:
  postgres_data: {}